### ISSUE TITLE
Consecutive hinged bone

### ISSUE THREAD

**Issue by aeciolevy-ven** [lo-th/fullik#6]
Firstly, thanks for developing the library.

I am having some problems to run a solver with 3 bones where the 2 last are consecutive Hinged Bone.

My base bone is with `Y_UP`

These are my second 
```js
lChain.addConsecutiveHingedBone(new FIK.V3(lAxisBone.x(), lAxisBone.y(), lAxisBone.z()), ilib_tm.mag(lDiff), 'global', new FIK.V3(lAxis.x(), lAxis.y(), lAxis.z()), -70, 90, new FIK.V3(lHingeReference.x(), lHingeReference.y(), lHingeReference.z()));
```
and third bone
```js
lChain.addConsecutiveHingedBone(new FIK.V3(lAxisBone.x(), lAxisBone.y(), lAxisBone.z()), ilib_tm.mag(lDiff), 'global', new FIK.V3(lAxis.x(), lAxis.y(), lAxis.z()), 135, 70, new FIK.V3(lHingeReference.x(), lHingeReference.y(), lHingeReference.z()));
```
It works if I am moving only one bone.
It partially works when I move forwarding with more than one bone. It does not work when I moving backward affect two bones.
Please find attached the gif that shows it partially working.
![2019-10-11 14 42 31](https://user-images.githubusercontent.com/45762503/66676482-92185200-ec35-11e9-9706-0c3c2f07b2cb.gif)

This is the GIF showing that moving more than one bone simultaneously does not seems to constrain the angle
![2019-10-11 14 43 01](https://user-images.githubusercontent.com/45762503/66676558-c986fe80-ec35-11e9-9d25-9c24c48e5cf9.gif)

Any thoughts?

**Comment by aeciolevy-ven** [comment]
Well, I am probably using the parameters wrong. 
What actually changes from local to global?

**Comment by aeciolevy-ven** [comment]
I am closing this issue, I got it working...
If you don't mind I would like a little bit of explaining the major difference between the `local` and `global` on the HingeBone.

**Comment by lo-th** [comment]
great, yes i'm thinking about update 
you can look caliko doc
